# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mClaeVk-uHRmdCkhimrbLPw7okOJK_Hc
"""

# app.py

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title('Auto Insurance Premium Prediction')

st.write("""
This is a simple demo app showing insights from the insurance premium prediction project.
""")

# Upload data
uploaded_file = st.file_uploader("insurance_data", type=["csv"])

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.write("Data Preview:")
    st.dataframe(data.head())

    st.write("**Premium Amount Distribution**")
    plt.figure(figsize=(8,4))
    sns.histplot(data['Premium_Amount'], kde=True)
    st.pyplot(plt.gcf())

st.write("---")
st.write("Developed by Prisha Bandyopadhyay for DSCI 441.")